import { PrismaClient, Gender } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

const DEMO_PASSWORD = 'Demo123!' // Same password for all demo accounts

interface DemoUser {
  name: string
  email: string
  gender: Gender
  birthDate: Date
  city: string
  postcode: string
  latitude: number
  longitude: number
  bio: string
  interests: string
  profileImage?: string
}

const demoUsers: DemoUser[] = [
  // Amsterdam profielen (1-15)
  {
    name: 'Sophie van den Berg',
    email: 'sophie@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1995-03-15'),
    city: 'Amsterdam',
    postcode: '1012',
    latitude: 52.3676,
    longitude: 4.9041,
    bio: 'Avonturierlijke ziel met een passie voor reizen en fotografie 📸 Op zoek naar iemand om de wereld mee te ontdekken! Liefhebber van goede koffie en diepe gesprekken.',
    interests: 'Reizen, Fotografie, Yoga, Koken, Wandelen',
    profileImage: 'https://i.pravatar.cc/400?img=1',
  },
  {
    name: 'Daan Peters',
    email: 'daan@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1993-02-14'),
    city: 'Amsterdam',
    postcode: '1017',
    latitude: 52.3555,
    longitude: 4.8838,
    bio: 'Architect en foodie 🍕 Altijd op zoek naar de beste restaurants in de stad. Hou van fietsen, design en goede muziek. Swipe right voor foodie dates!',
    interests: 'Architectuur, Eten, Fietsen, Design, Muziek',
    profileImage: 'https://i.pravatar.cc/400?img=14',
  },
  {
    name: 'Luna Vermeer',
    email: 'luna@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1996-06-20'),
    city: 'Amsterdam',
    postcode: '1075',
    latitude: 52.3547,
    longitude: 4.8707,
    bio: 'Creative director met een voorliefde voor straatkunst en vintage fashion 🎨 Weekenden besteed ik in musea of op terrasjes. Zoek iemand die net zo houdt van spontane avonturen!',
    interests: 'Kunst, Mode, Muziek, Festivals, Fotografie',
    profileImage: 'https://i.pravatar.cc/400?img=2',
  },
  {
    name: 'Tim Bosman',
    email: 'tim@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1991-09-08'),
    city: 'Amsterdam',
    postcode: '1054',
    latitude: 52.3667,
    longitude: 4.8645,
    bio: 'Data scientist die graag kookt en experimenteert in de keuken 👨‍🍳 Opzoek naar iemand die van lekker eten en goede gesprekken houdt. Bonus: je houdt van sciencefiction!',
    interests: 'Koken, Tech, Gaming, Lezen, Films',
    profileImage: 'https://i.pravatar.cc/400?img=11',
  },
  {
    name: 'Iris de Wit',
    email: 'iris@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1994-11-30'),
    city: 'Amsterdam',
    postcode: '1091',
    latitude: 52.3571,
    longitude: 4.9138,
    bio: 'Marketing manager en yogaliefhebber 🧘‍♀️ Balans tussen carrière en mindfulness is mijn ding. Hou van brunchen, goede wijn en diepgaande gesprekken. Zoek een ambitieuze maar relaxte match!',
    interests: 'Yoga, Marketing, Reizen, Wijn, Mindfulness',
    profileImage: 'https://i.pravatar.cc/400?img=3',
  },
  {
    name: 'Jasper Krol',
    email: 'jasper@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1990-04-12'),
    city: 'Amsterdam',
    postcode: '1013',
    latitude: 52.3881,
    longitude: 4.8892,
    bio: 'Entrepreneur met passie voor duurzaamheid 🌱 Bouw aan de toekomst overdag, geniet van live muziek s avonds. Zoek een partner die ook van aanpakken houdt!',
    interests: 'Duurzaamheid, Ondernemen, Muziek, Festivals, Fietsen',
    profileImage: 'https://i.pravatar.cc/400?img=18',
  },
  {
    name: 'Fleur Dijkstra',
    email: 'fleur@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1997-07-25'),
    city: 'Amsterdam',
    postcode: '1018',
    latitude: 52.3615,
    longitude: 4.9124,
    bio: 'Journaliste en podcastliefhebber 🎙️ Altijd nieuwsgierig naar verhalen en mensen. Hou van hardlopen door het Vondelpark en nieuwe restaurants ontdekken. Swipe voor goede gesprekken!',
    interests: 'Journalistiek, Podcasts, Hardlopen, Eten, Reizen',
    profileImage: 'https://i.pravatar.cc/400?img=4',
  },
  {
    name: 'Ruben van Loon',
    email: 'ruben@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1992-12-05'),
    city: 'Amsterdam',
    postcode: '1071',
    latitude: 52.3517,
    longitude: 4.8776,
    bio: 'DJ en muziekproducent 🎧 Als ik niet in de studio zit, ben ik op festivals of aan het raven. Zoek iemand die net zo van elektronische muziek houdt. Nachtuiltjes voor!',
    interests: 'Muziek, Festivals, Uitgaan, Productie, Vinyl',
    profileImage: 'https://i.pravatar.cc/400?img=19',
  },
  {
    name: 'Anna Hoekstra',
    email: 'anna@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1995-01-18'),
    city: 'Amsterdam',
    postcode: '1078',
    latitude: 52.3422,
    longitude: 4.8945,
    bio: 'Kinderarts met een hart van goud ❤️ Werk hard, ontspan graag met vrienden en familie. Droom van wereldreizen en avontuur. Zoek iemand lief en grappig!',
    interests: 'Geneeskunde, Reizen, Familie, Koken, Lezen',
    profileImage: 'https://i.pravatar.cc/400?img=6',
  },
  {
    name: 'Sem Verhoeven',
    email: 'sem@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1993-08-14'),
    city: 'Amsterdam',
    postcode: '1055',
    latitude: 52.3745,
    longitude: 4.8567,
    bio: 'Personal trainer en gezondheidsfreak 💪 Fitness is mijn passie, maar ik hou ook van goede pizza! Zoek iemand actief die van sporten en lekker eten houdt. Balance is key!',
    interests: 'Fitness, Gezondheid, Voeding, Sport, Reizen',
    profileImage: 'https://i.pravatar.cc/400?img=20',
  },
  {
    name: 'Eva Mulder',
    email: 'eva@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1996-03-22'),
    city: 'Amsterdam',
    postcode: '1052',
    latitude: 52.3676,
    longitude: 4.8551,
    bio: 'Interior designer met een obsessie voor planten 🌿 Mijn huis is een jungle en ik wil niks anders! Hou van vintage markten, sustainability en gezellige avondjes thuis.',
    interests: 'Design, Planten, Vintage, Duurzaamheid, Kunst',
    profileImage: 'https://i.pravatar.cc/400?img=7',
  },
  {
    name: 'Lars Meijer',
    email: 'lars@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1994-10-09'),
    city: 'Amsterdam',
    postcode: '1092',
    latitude: 52.3545,
    longitude: 4.9234,
    bio: 'Fotograaf die de wereld door een lens ziet 📷 Altijd op zoek naar het perfecte shot. Hou van reizen, koffie en spontane avonturen. Swipe right als je model wilt zijn! 😉',
    interests: 'Fotografie, Reizen, Koffie, Kunst, Avontuur',
    profileImage: 'https://i.pravatar.cc/400?img=21',
  },
  {
    name: 'Nina Scholten',
    email: 'nina@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1998-05-16'),
    city: 'Amsterdam',
    postcode: '1072',
    latitude: 52.3489,
    longitude: 4.8901,
    bio: 'Studente mode en vintage lover 👗 Geobsedeerd door thrifting en sustainable fashion. Zoek iemand creatief en open-minded voor museum dates en festivals!',
    interests: 'Mode, Vintage, Kunst, Festivals, Duurzaamheid',
    profileImage: 'https://i.pravatar.cc/400?img=8',
  },
  {
    name: 'Stijn Dekker',
    email: 'stijn@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1991-07-03'),
    city: 'Amsterdam',
    postcode: '1019',
    latitude: 52.3712,
    longitude: 4.9456,
    bio: 'Advocaat en wijnliefhebber 🍷 Werk hard, geniet harder. Hou van diners, theater en weekendjes weg. Zoek iemand ambitieus en cultureel geïnteresseerd.',
    interests: 'Wijn, Recht, Theater, Reizen, Cultuur',
    profileImage: 'https://i.pravatar.cc/400?img=22',
  },
  {
    name: 'Zara Bakker',
    email: 'zara@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1995-09-28'),
    city: 'Amsterdam',
    postcode: '1053',
    latitude: 52.3689,
    longitude: 4.8423,
    bio: 'Event manager die van gezelligheid houdt 🎉 Organiseer van kleine borrels tot grote festivals. Hou van dansen, lachen en nieuwe mensen ontmoeten. Zoek een sociaal en spontaan persoon!',
    interests: 'Events, Dansen, Uitgaan, Organiseren, Vrienden',
    profileImage: 'https://i.pravatar.cc/400?img=9',
  },

  // Rotterdam profielen (16-25)
  {
    name: 'Liam de Vries',
    email: 'liam@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1992-07-22'),
    city: 'Rotterdam',
    postcode: '3011',
    latitude: 51.9244,
    longitude: 4.4777,
    bio: 'Software engineer bij dag, drummer bij nacht 🥁 Zoek iemand die van festivals en spontane roadtrips houdt. Kan een killer pasta maken!',
    interests: 'Muziek, Programmeren, Festivals, Fitness, Gaming',
    profileImage: 'https://i.pravatar.cc/400?img=12',
  },
  {
    name: 'Olivia Verburg',
    email: 'olivia@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1994-04-11'),
    city: 'Rotterdam',
    postcode: '3012',
    latitude: 51.9225,
    longitude: 4.4792,
    bio: 'Havenfotograaf en stoere griet 📸 Rotterdam is mijn speeltuin! Hou van industriële architectuur, hardstyle en borrelen op het Witte de Withkwartier. Swipe voor echte 010 vibes!',
    interests: 'Fotografie, Architectuur, Uitgaan, Hardstyle, Cultuur',
    profileImage: 'https://i.pravatar.cc/400?img=13',
  },
  {
    name: 'Milan Brouwer',
    email: 'milan@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1993-11-07'),
    city: 'Rotterdam',
    postcode: '3024',
    latitude: 51.9067,
    longitude: 4.4856,
    bio: 'Scheepsbouwkundig ingenieur met passie voor zeilen ⛵ Weekenden op het water, door de weeks innoveren. Zoek iemand avontuurlijk die ook van de zee houdt!',
    interests: 'Zeilen, Engineering, Reizen, Water, Avontuur',
    profileImage: 'https://i.pravatar.cc/400?img=23',
  },
  {
    name: 'Sanne Groot',
    email: 'sanne@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1996-02-19'),
    city: 'Rotterdam',
    postcode: '3013',
    latitude: 51.9178,
    longitude: 4.4856,
    bio: 'Verpleegkundige en yogadocent 🧘‍♀️ Help mensen graag, zowel fysiek als mentaal. Hou van gezond leven maar ook van een goed terrasje! Zoek balans en gezelligheid.',
    interests: 'Yoga, Gezondheid, Wandelen, Mindfulness, Vrienden',
    profileImage: 'https://i.pravatar.cc/400?img=14',
  },
  {
    name: 'Jesse van Dam',
    email: 'jesse@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1990-06-15'),
    city: 'Rotterdam',
    postcode: '3021',
    latitude: 51.9145,
    longitude: 4.4667,
    bio: 'Eigenaar van een koffiezaak ☕ Koffie is mijn passie, hospitality mijn talent. Hou van jazz, goede gesprekken en de nieuwste coffee trends. Swipe voor de beste cappuccino!',
    interests: 'Koffie, Horeca, Jazz, Reizen, Eten',
    profileImage: 'https://i.pravatar.cc/400?img=24',
  },
  {
    name: 'Isa Peters',
    email: 'isa@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1997-08-23'),
    city: 'Rotterdam',
    postcode: '3014',
    latitude: 51.9156,
    longitude: 4.4678,
    bio: 'Psychologie student en festival junkie 🎪 Geobsedeerd door menselijk gedrag en goede muziek. Hou van dansen, diepgaande gesprekken en spontane avonturen!',
    interests: 'Psychologie, Festivals, Muziek, Dansen, Lezen',
    profileImage: 'https://i.pravatar.cc/400?img=15',
  },
  {
    name: 'Finn Jacobs',
    email: 'finn@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1995-12-30'),
    city: 'Rotterdam',
    postcode: '3015',
    latitude: 51.9089,
    longitude: 4.4678,
    bio: 'Grafisch ontwerper en streetart liefhebber 🎨 Design is overal! Hou van skaten, vintage kleding en urban culture. Zoek een creatieve match voor museum dates!',
    interests: 'Design, Streetart, Skaten, Mode, Kunst',
    profileImage: 'https://i.pravatar.cc/400?img=25',
  },
  {
    name: 'Yara Smeets',
    email: 'yara@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1993-03-08'),
    city: 'Rotterdam',
    postcode: '3033',
    latitude: 51.9267,
    longitude: 4.4889,
    bio: 'Tandarts met een mooie glimlach 😁 Hou van hardlopen, brunchen en citytrips. Zoek iemand sportief en sociaal voor leuke dates en avonturen. Tanden poetsen is wel verplicht! 😉',
    interests: 'Hardlopen, Reizen, Brunchen, Sport, Vrienden',
    profileImage: 'https://i.pravatar.cc/400?img=16',
  },
  {
    name: 'Mees Willems',
    email: 'mees@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1991-09-17'),
    city: 'Rotterdam',
    postcode: '3016',
    latitude: 51.9123,
    longitude: 4.4545,
    bio: 'Sales manager en netwerker 🤝 Mensen zijn mijn passie! Hou van golfen, zakelijke diners en goede whiskey. Zoek een ambitieuze partner voor succesvolle dates!',
    interests: 'Sales, Golf, Netwerken, Whiskey, Reizen',
    profileImage: 'https://i.pravatar.cc/400?img=26',
  },
  {
    name: 'Noor de Vos',
    email: 'noor@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1998-01-12'),
    city: 'Rotterdam',
    postcode: '3022',
    latitude: 51.9178,
    longitude: 4.4523,
    bio: 'Fashion student en trendsetter 👠 Altijd bezig met de nieuwste mode trends. Hou van shoppen, Instagram en brunchen. Zoek iemand stylish en fun!',
    interests: 'Mode, Shopping, Social Media, Brunchen, Vrienden',
    profileImage: 'https://i.pravatar.cc/400?img=17',
  },

  // Utrecht profielen (26-33)
  {
    name: 'Emma Bakker',
    email: 'emma@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1997-11-08'),
    city: 'Utrecht',
    postcode: '3511',
    latitude: 52.0907,
    longitude: 5.1214,
    bio: 'Grafisch ontwerper met een zwak voor vintage markten en plantjes 🌿 Zoek een partner in crime voor museums en brunch dates. Bonus points voor hondenmensen!',
    interests: 'Design, Kunst, Vintage, Planten, Honden',
    profileImage: 'https://i.pravatar.cc/400?img=5',
  },
  {
    name: 'Bram Koning',
    email: 'bram@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1992-05-25'),
    city: 'Utrecht',
    postcode: '3512',
    latitude: 52.0889,
    longitude: 5.1178,
    bio: 'Leraar geschiedenis en museum junkie 📚 Hou van fietsen langs de grachten en goede discussies. Zoek iemand slim en nieuwsgierig. Geschiedenisnerds welkom!',
    interests: 'Geschiedenis, Musea, Fietsen, Lezen, Cultuur',
    profileImage: 'https://i.pravatar.cc/400?img=27',
  },
  {
    name: 'Roos Janssen',
    email: 'roos@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1995-07-14'),
    city: 'Utrecht',
    postcode: '3521',
    latitude: 52.0845,
    longitude: 5.1289,
    bio: 'Dierenarts en kattengek 🐱 Mijn hart gaat uit naar alle dieren! Hou van wandelen in het bos, Netflix marathons en gezellige dates. Zoek een dierenvriend!',
    interests: 'Dieren, Natuur, Wandelen, Series, Koken',
    profileImage: 'https://i.pravatar.cc/400?img=18',
  },
  {
    name: 'Lucas Jansen',
    email: 'lucas@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1993-10-03'),
    city: 'Utrecht',
    postcode: '3513',
    latitude: 52.0923,
    longitude: 5.1245,
    bio: 'Financial consultant en sportfanaat ⚽ Voetbal kijken op zondag is heilig! Hou van fitness, borrelen en weekendjes weg. Zoek een sportieve en gezellige match!',
    interests: 'Voetbal, Fitness, Finance, Borrelen, Reizen',
    profileImage: 'https://i.pravatar.cc/400?img=28',
  },
  {
    name: 'Sara Visser',
    email: 'sara@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1996-12-20'),
    city: 'Utrecht',
    postcode: '3514',
    latitude: 52.0856,
    longitude: 5.1167,
    bio: 'HR manager en peopleperson 💼 Hou van mooie gesprekken en mensen ontwikkelen. Zoek iemand empathisch en ambitieus. Liefde voor boeken is een plus!',
    interests: 'HR, Lezen, Psychologie, Wandelen, Theater',
    profileImage: 'https://i.pravatar.cc/400?img=19',
  },
  {
    name: 'Robin de Boer',
    email: 'robin@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1994-04-17'),
    city: 'Utrecht',
    postcode: '3522',
    latitude: 52.0789,
    longitude: 5.1312,
    bio: 'Game developer en nerd 🎮 Gaming is mijn passie en werk! Hou van anime, boardgames en pizza. Zoek een geek die begrijpt waarom ik s nachts nog game 😄',
    interests: 'Gaming, Programmeren, Anime, Boardgames, Tech',
    profileImage: 'https://i.pravatar.cc/400?img=29',
  },
  {
    name: 'Lotte Hendriks',
    email: 'lotte@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1997-06-09'),
    city: 'Utrecht',
    postcode: '3531',
    latitude: 52.0967,
    longitude: 5.1078,
    bio: 'Barista en koffieliefhebber ☕ Latte art is mijn kunst! Hou van indie muziek, festivals en spontane roadtrips. Swipe voor de beste flat white van Utrecht!',
    interests: 'Koffie, Muziek, Festivals, Reizen, Kunst',
    profileImage: 'https://i.pravatar.cc/400?img=20',
  },
  {
    name: 'Thijs Vermeulen',
    email: 'thijs.vermeulen@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1990-08-28'),
    city: 'Utrecht',
    postcode: '3541',
    latitude: 52.1023,
    longitude: 5.0934,
    bio: 'Architect en wielrenner 🚴‍♂️ Design meets sport! Hou van lange fietstochten, moderne architectuur en goede koffie. Zoek een actieve match voor sportieve dates!',
    interests: 'Wielrennen, Architectuur, Koffie, Design, Sport',
    profileImage: 'https://i.pravatar.cc/400?img=30',
  },

  // Den Haag profielen (34-41)
  {
    name: 'Noah Jansen',
    email: 'noah@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1990-05-30'),
    city: 'Den Haag',
    postcode: '2511',
    latitude: 52.0705,
    longitude: 4.3007,
    bio: 'Advocaat die graag hardloopt langs het strand 🏃‍♂️ Fan van goede wijn, betere gesprekken en spontane weekendjes weg. Zoek iemand ambitieus maar down-to-earth.',
    interests: 'Hardlopen, Wijn, Reizen, Lezen, Politiek',
    profileImage: 'https://i.pravatar.cc/400?img=13',
  },
  {
    name: 'Sofie Schouten',
    email: 'sofie@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1995-09-12'),
    city: 'Den Haag',
    postcode: '2512',
    latitude: 52.0778,
    longitude: 4.3134,
    bio: 'Diplomaat en taalenfanaat 🌍 Werk bij Internationale organisaties. Spreek 5 talen! Hou van cultuur, reizen en diepgaande gesprekken. Zoek iemand werelds!',
    interests: 'Politiek, Talen, Reizen, Cultuur, Lezen',
    profileImage: 'https://i.pravatar.cc/400?img=21',
  },
  {
    name: 'Dylan Visser',
    email: 'dylan@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1993-03-19'),
    city: 'Den Haag',
    postcode: '2513',
    latitude: 52.0689,
    longitude: 4.3167,
    bio: 'Surflehrer en strandliefhebber 🏄‍♂️ Scheveningen is mijn thuis! Hou van surfen, beachvolleybal en BBQs op het strand. Zoek een actieve beach babe!',
    interests: 'Surfen, Strand, Sport, Outdoors, Reizen',
    profileImage: 'https://i.pravatar.cc/400?img=31',
  },
  {
    name: 'Lisa de Jong',
    email: 'lisa.dejong@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1996-11-05'),
    city: 'Den Haag',
    postcode: '2514',
    latitude: 52.0723,
    longitude: 4.3089,
    bio: 'Journaliste bij een groot dagblad 📰 Altijd op zoek naar het volgende verhaal. Hou van politiek, kunst en goede wijn. Zoek iemand die kritisch kan denken!',
    interests: 'Journalistiek, Politiek, Kunst, Wijn, Theater',
    profileImage: 'https://i.pravatar.cc/400?img=22',
  },
  {
    name: 'Jayden Bakker',
    email: 'jayden@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1992-07-24'),
    city: 'Den Haag',
    postcode: '2515',
    latitude: 52.0645,
    longitude: 4.3223,
    bio: 'Chef-kok met Michelin ambities 👨‍🍳 Eten is liefde! Hou van culinaire experimenten en goede wijn. Zoek een foodie voor smakelijke dates. Koken voor jou? Sure!',
    interests: 'Koken, Eten, Wijn, Reizen, Restaurants',
    profileImage: 'https://i.pravatar.cc/400?img=32',
  },
  {
    name: 'Maya Smit',
    email: 'maya@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1994-02-16'),
    city: 'Den Haag',
    postcode: '2516',
    latitude: 52.0667,
    longitude: 4.3156,
    bio: 'Yoga instructeur en wellness guru 🧘‍♀️ Balance en mindfulness zijn key. Hou van gezond leven, meditatie en nature walks. Zoek inner peace together?',
    interests: 'Yoga, Mindfulness, Wellness, Natuur, Gezondheid',
    profileImage: 'https://i.pravatar.cc/400?img=23',
  },
  {
    name: 'Teun Jansen',
    email: 'teun@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1991-12-01'),
    city: 'Den Haag',
    postcode: '2517',
    latitude: 52.0689,
    longitude: 4.2989,
    bio: 'Startup founder en tech enthusiast 💻 Building the future! Hou van innovatie, networking en festivals. Zoek een ondernemende match. Let s disrupt together!',
    interests: 'Tech, Startups, Innovatie, Festivals, Netwerken',
    profileImage: 'https://i.pravatar.cc/400?img=33',
  },
  {
    name: 'Zoë Peters',
    email: 'zoe@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1998-04-13'),
    city: 'Den Haag',
    postcode: '2518',
    latitude: 52.0812,
    longitude: 4.2878,
    bio: 'Studente international relations 🌍 Wil de wereld verbeteren! Hou van debatteren, reizen en nieuwe culturen. Zoek iemand met visie en passie!',
    interests: 'Politiek, Reizen, Debatteren, Cultuur, Lezen',
    profileImage: 'https://i.pravatar.cc/400?img=24',
  },

  // Haarlem, Leiden en overige Randstad (42-50)
  {
    name: 'Thijs van Dijk',
    email: 'thijs@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1991-08-25'),
    city: 'Haarlem',
    postcode: '2011',
    latitude: 52.3874,
    longitude: 4.6462,
    bio: 'Marketing manager en sportfanaat ⚽ Voetbal op zondag, borrelen op vrijdag. Zoek iemand spontaan en sociaal voor leuke dates en avonturen.',
    interests: 'Voetbal, Marketing, Fitness, Uitgaan, Vrienden',
    profileImage: 'https://i.pravatar.cc/400?img=15',
  },
  {
    name: 'Mila Visser',
    email: 'mila@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1998-04-19'),
    city: 'Leiden',
    postcode: '2311',
    latitude: 52.1601,
    longitude: 4.4970,
    bio: 'Student psychologie met een passie voor theater en dans 💃 Hou van diepe gesprekken en lachen tot je buikpijn hebt. Zoek een creatieve ziel!',
    interests: 'Psychologie, Theater, Dansen, Muziek, Festivals',
    profileImage: 'https://i.pravatar.cc/400?img=16',
  },
  {
    name: 'Owen Mulder',
    email: 'owen@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1994-01-07'),
    city: 'Almere',
    postcode: '1315',
    latitude: 52.3508,
    longitude: 5.2647,
    bio: 'IT consultant en gamer 🎮 Tech is mijn leven! Hou van gaming, anime en goede series. Zoek een nerd die begrijpt waarom RGB lighting belangrijk is 😄',
    interests: 'Gaming, Tech, Anime, Series, Programmeren',
    profileImage: 'https://i.pravatar.cc/400?img=34',
  },
  {
    name: 'Evi Smeets',
    email: 'evi@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1995-10-22'),
    city: 'Zaandam',
    postcode: '1506',
    latitude: 52.4389,
    longitude: 4.8258,
    bio: 'Apotheker en health enthusiast 💊 Help mensen graag! Hou van hardlopen, healthy cooking en mindfulness. Zoek iemand die ook van een gezonde lifestyle houdt!',
    interests: 'Gezondheid, Hardlopen, Koken, Mindfulness, Wetenschap',
    profileImage: 'https://i.pravatar.cc/400?img=25',
  },
  {
    name: 'Cas Willems',
    email: 'cas@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1993-06-18'),
    city: 'Delft',
    postcode: '2611',
    latitude: 52.0116,
    longitude: 4.3571,
    bio: 'Werktuigbouwkundig ingenieur en maker 🔧 Altijd bezig met bouwen en ontwerpen. Hou van tech, wielrennen en craft beer. Zoek iemand nieuwsgierig!',
    interests: 'Engineering, Tech, Wielrennen, Beer, Maken',
    profileImage: 'https://i.pravatar.cc/400?img=35',
  },
  {
    name: 'Noa Koolen',
    email: 'noa@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1997-03-27'),
    city: 'Amstelveen',
    postcode: '1181',
    latitude: 52.3008,
    longitude: 4.8632,
    bio: 'Social media manager en content creator 📱 Instagram is mijn canvas! Hou van fotografie, reizen en brunch. Zoek iemand fotogeniek voor insta-worthy dates!',
    interests: 'Social Media, Fotografie, Reizen, Brunchen, Mode',
    profileImage: 'https://i.pravatar.cc/400?img=26',
  },
  {
    name: 'Jelle Prins',
    email: 'jelle@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1992-09-14'),
    city: 'Hoofddorp',
    postcode: '2132',
    latitude: 52.3025,
    longitude: 4.6892,
    bio: 'Piloot en adventure seeker ✈️ De wereld is mijn kantoor! Hou van reizen, extreme sporten en nieuwe ervaringen. Zoek iemand avontuurlijk. Sky is NOT the limit!',
    interests: 'Vliegen, Reizen, Extreme sporten, Avontuur, Fotografie',
    profileImage: 'https://i.pravatar.cc/400?img=36',
  },
  {
    name: 'Liv Dekkers',
    email: 'liv@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1996-05-08'),
    city: 'Hilversum',
    postcode: '1211',
    latitude: 52.2309,
    longitude: 5.1766,
    bio: 'Radio DJ en muziekjunkie 🎵 Muziek is mijn leven! Hou van live concerts, festivals en vinyl verzamelen. Zoek iemand die ook altijd muziek aan heeft staan!',
    interests: 'Muziek, Radio, Festivals, Vinyl, Uitgaan',
    profileImage: 'https://i.pravatar.cc/400?img=27',
  },
  {
    name: 'Sam de Groot',
    email: 'sam@demo.nl',
    gender: Gender.MALE,
    birthDate: new Date('1990-11-19'),
    city: 'Haarlem',
    postcode: '2013',
    latitude: 52.3812,
    longitude: 4.6389,
    bio: 'Eigenaar van een craft brewery 🍺 Bier brouwen is kunst! Hou van experimenten, proeverijen en gezelligheid. Swipe voor een biertje en goed gesprek!',
    interests: 'Bier, Brouwen, Horeca, Eten, Gezelligheid',
    profileImage: 'https://i.pravatar.cc/400?img=37',
  },
  {
    name: 'Ivy Scholten',
    email: 'ivy@demo.nl',
    gender: Gender.FEMALE,
    birthDate: new Date('1995-08-31'),
    city: 'Leiden',
    postcode: '2312',
    latitude: 52.1589,
    longitude: 4.4923,
    bio: 'Biomedisch onderzoeker en science nerd 🔬 Fascinatie voor alles wat met het menselijk lichaam te maken heeft. Hou van lezen, musea en intellectuele gesprekken!',
    interests: 'Wetenschap, Onderzoek, Lezen, Musea, Leren',
    profileImage: 'https://i.pravatar.cc/400?img=28',
  },
]

async function main() {
  console.log('🌱 Starting seed...')

  // Hash the demo password once
  const passwordHash = await bcrypt.hash(DEMO_PASSWORD, 12)

  // Create demo users
  for (const userData of demoUsers) {
    const user = await prisma.user.upsert({
      where: { email: userData.email },
      update: {},
      create: {
        ...userData,
        passwordHash,
        emailVerified: new Date(),
        isVerified: true,
        hasAcceptedTerms: true,
        safetyScore: 100,
        role: 'USER',
      },
    })

    console.log(`✅ Created/verified user: ${user.name} (${user.email})`)

    // Add profile photo
    if (userData.profileImage) {
      const existingPhoto = await prisma.photo.findFirst({
        where: { userId: user.id },
      })

      if (!existingPhoto) {
        await prisma.photo.create({
          data: {
            userId: user.id,
            url: userData.profileImage,
            order: 0,
          },
        })
      }
    }
  }

  console.log('\n🎉 Seed completed successfully!')
  console.log('\n📝 Demo Account Credentials:')
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
  console.log('Password for ALL accounts: Demo123!')
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
  demoUsers.forEach((user) => {
    console.log(`📧 ${user.email.padEnd(25)} | ${user.name} (${user.city})`)
  })
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n')
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
