/**
 * Export complete database to SQL file
 */

import { prisma } from '../lib/prisma'
import fs from 'fs'
import path from 'path'

async function exportDatabase() {
  const outputPath = path.join(process.cwd(), 'Huidigedatabase', 'oudedatabase.sql')

  console.log('🔄 Exporting database...\n')

  let sql = `-- Database Export: ${new Date().toISOString()}\n`
  sql += `-- Generated by Prisma\n\n`
  sql += `SET client_encoding = 'UTF8';\n\n`

  try {
    // Export Users
    console.log('📊 Exporting Users...')
    const users = await prisma.user.findMany()
    sql += `-- Users (${users.length} records)\n`
    for (const user of users) {
      const values = [
        user.id,
        user.name ? `'${user.name.replace(/'/g, "''")}'` : 'NULL',
        user.email ? `'${user.email.replace(/'/g, "''")}'` : 'NULL',
        user.emailVerified ? `'${user.emailVerified.toISOString()}'` : 'NULL',
        user.image ? `'${user.image.replace(/'/g, "''")}'` : 'NULL',
        user.passwordHash ? `'${user.passwordHash.replace(/'/g, "''")}'` : 'NULL',
        user.bio ? `'${user.bio.replace(/'/g, "''")}'` : 'NULL',
        user.birthDate ? `'${user.birthDate.toISOString()}'` : 'NULL',
        user.gender ? `'${user.gender}'` : 'NULL',
        user.city ? `'${user.city.replace(/'/g, "''")}'` : 'NULL',
        user.postcode ? `'${user.postcode.replace(/'/g, "''")}'` : 'NULL',
        user.interests ? `'${JSON.stringify(user.interests).replace(/'/g, "''")}'` : 'NULL',
        user.preferences ? `'${JSON.stringify(user.preferences).replace(/'/g, "''")}'` : 'NULL',
        user.profileImage ? `'${user.profileImage.replace(/'/g, "''")}'` : 'NULL',
        user.voiceIntro ? `'${user.voiceIntro.replace(/'/g, "''")}'` : 'NULL',
        user.role ? `'${user.role}'` : 'NULL',
        user.isVerified ? user.isVerified : 'false',
        user.safetyScore !== null ? user.safetyScore : 'NULL',
        user.hasAcceptedTerms ? user.hasAcceptedTerms : 'false',
        user.latitude !== null ? user.latitude : 'NULL',
        user.longitude !== null ? user.longitude : 'NULL',
        user.twoFactorSecret ? `'${user.twoFactorSecret.replace(/'/g, "''")}'` : 'NULL',
        user.twoFactorEnabled ? user.twoFactorEnabled : 'false',
        user.twoFactorBackupCodes ? `'${user.twoFactorBackupCodes.replace(/'/g, "''")}'` : 'NULL',
        `'${user.createdAt.toISOString()}'`,
        `'${user.updatedAt.toISOString()}'`
      ]
      sql += `INSERT INTO "User" VALUES (${values.join(', ')});\n`
    }
    sql += '\n'

    // Export Photos
    console.log('📸 Exporting Photos...')
    const photos = await prisma.photo.findMany()
    sql += `-- Photos (${photos.length} records)\n`
    for (const photo of photos) {
      const values = [
        photo.id,
        `'${photo.url.replace(/'/g, "''")}'`,
        photo.order,
        `'${photo.userId}'`,
        `'${new Date().toISOString()}'`
      ]
      sql += `INSERT INTO "Photo" VALUES (${values.join(', ')});\n`
    }
    sql += '\n'

    // Export Matches
    console.log('💕 Exporting Matches...')
    const matches = await prisma.match.findMany()
    sql += `-- Matches (${matches.length} records)\n`
    for (const match of matches) {
      const values = [
        match.id,
        `'${match.user1Id}'`,
        `'${match.user2Id}'`,
        match.createdAt ? `'${match.createdAt.toISOString()}'` : `'${new Date().toISOString()}'`
      ]
      sql += `INSERT INTO "Match" VALUES (${values.join(', ')});\n`
    }
    sql += '\n'

    // Export Messages
    console.log('💬 Exporting Messages...')
    const messages = await prisma.message.findMany()
    sql += `-- Messages (${messages.length} records)\n`
    for (const message of messages) {
      const values = [
        message.id,
        `'${message.matchId}'`,
        `'${message.senderId}'`,
        `'${message.content.replace(/'/g, "''")}'`,
        message.isRead ? 'true' : 'false',
        message.createdAt ? `'${message.createdAt.toISOString()}'` : `'${new Date().toISOString()}'`
      ]
      sql += `INSERT INTO "Message" VALUES (${values.join(', ')});\n`
    }
    sql += '\n'

    // Export Swipes
    console.log('👆 Exporting Swipes...')
    const swipes = await prisma.swipe.findMany()
    sql += `-- Swipes (${swipes.length} records)\n`
    for (const swipe of swipes) {
      const values = [
        swipe.id,
        `'${swipe.swiperId}'`,
        `'${swipe.swipedId}'`,
        `'${swipe.type}'`,
        swipe.createdAt ? `'${swipe.createdAt.toISOString()}'` : `'${new Date().toISOString()}'`
      ]
      sql += `INSERT INTO "Swipe" VALUES (${values.join(', ')});\n`
    }
    sql += '\n'

    // Export EmailLogs
    console.log('📧 Exporting EmailLogs...')
    const emailLogs = await prisma.emailLog.findMany()
    sql += `-- EmailLogs (${emailLogs.length} records)\n`
    for (const log of emailLogs) {
      const values = [
        log.id,
        log.userId ? `'${log.userId}'` : 'NULL',
        `'${log.email.replace(/'/g, "''")}'`,
        `'${log.subject.replace(/'/g, "''")}'`,
        `'${log.type}'`,
        `'${log.category}'`,
        `'${log.status}'`,
        log.resendId ? `'${log.resendId.replace(/'/g, "''")}'` : 'NULL',
        log.deliveredAt ? `'${log.deliveredAt.toISOString()}'` : 'NULL',
        log.openedAt ? `'${log.openedAt.toISOString()}'` : 'NULL',
        log.clickedAt ? `'${log.clickedAt.toISOString()}'` : 'NULL',
        log.bouncedAt ? `'${log.bouncedAt.toISOString()}'` : 'NULL',
        log.failedAt ? `'${log.failedAt.toISOString()}'` : 'NULL',
        log.error ? `'${log.error.replace(/'/g, "''")}'` : 'NULL',
        `'${log.sentAt.toISOString()}'`
      ]
      sql += `INSERT INTO "EmailLog" VALUES (${values.join(', ')});\n`
    }
    sql += '\n'

    // Export Blocks
    console.log('🚫 Exporting Blocks...')
    const blocks = await prisma.block.findMany()
    sql += `-- Blocks (${blocks.length} records)\n`
    for (const block of blocks) {
      const values = [
        block.id,
        `'${block.blockerId}'`,
        `'${block.blockedId}'`,
        block.createdAt ? `'${block.createdAt.toISOString()}'` : `'${new Date().toISOString()}'`
      ]
      sql += `INSERT INTO "Block" VALUES (${values.join(', ')});\n`
    }
    sql += '\n'

    // Export Reports
    console.log('⚠️  Exporting Reports...')
    const reports = await prisma.report.findMany()
    sql += `-- Reports (${reports.length} records)\n`
    for (const report of reports) {
      const values = [
        report.id,
        `'${report.reporterId}'`,
        `'${report.reportedId}'`,
        `'${report.reason}'`,
        report.description ? `'${report.description.replace(/'/g, "''")}'` : 'NULL',
        `'${report.status}'`,
        report.reviewedBy ? `'${report.reviewedBy}'` : 'NULL',
        report.reviewedAt ? `'${report.reviewedAt.toISOString()}'` : 'NULL',
        report.actionTaken ? `'${report.actionTaken.replace(/'/g, "''")}'` : 'NULL',
        report.createdAt ? `'${report.createdAt.toISOString()}'` : `'${new Date().toISOString()}'`
      ]
      sql += `INSERT INTO "Report" VALUES (${values.join(', ')});\n`
    }
    sql += '\n'

    // Write to file
    fs.mkdirSync(path.dirname(outputPath), { recursive: true })
    fs.writeFileSync(outputPath, sql, 'utf8')

    console.log('\n✅ Export successful!')
    console.log(`📁 File: ${outputPath}`)
    console.log(`📊 Size: ${(sql.length / 1024).toFixed(2)} KB`)
    console.log('\n📋 Exported tables:')
    console.log(`   - Users: ${users.length}`)
    console.log(`   - Photos: ${photos.length}`)
    console.log(`   - Matches: ${matches.length}`)
    console.log(`   - Messages: ${messages.length}`)
    console.log(`   - Swipes: ${swipes.length}`)
    console.log(`   - EmailLogs: ${emailLogs.length}`)
    console.log(`   - Blocks: ${blocks.length}`)
    console.log(`   - Reports: ${reports.length}`)

  } catch (error) {
    console.error('❌ Export failed:', error)
    throw error
  } finally {
    await prisma.$disconnect()
  }
}

exportDatabase()
